color0 #131313
color1 #ffb4ab
color2 #c7bfff
color3 #c8c3dc
color4 #ecb8cf
color5 #c7bfff
color6 #c8c3dc
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #c7bfff
color11 #c8c3dc
color12 #ecb8cf
color13 #c7bfff
color14 #c8c3dc
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #c7bfff
inactive_border_color #474747
url_color             #c7bfff

active_tab_foreground   #2d2276
active_tab_background   #c7bfff
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
cursor_trail_color      #c6c6c6
