color0 #141316
color1 #ffb4ab
color2 #d0bcff
color3 #ccc2db
color4 #f0b8c7
color5 #d0bcff
color6 #ccc2db
color7 #e6e1e6
color8 #948f99
color9 #ffb4ab
color10 #d0bcff
color11 #ccc2db
color12 #f0b8c7
color13 #d0bcff
color14 #ccc2db
color15 #e6e1e6

cursor                #e6e1e6
cursor_text_color     #141316
background            #141316
foreground            #e6e1e6
selection_foreground  #cac4cf
selection_background  #49454e
active_border_color   #d0bcff
inactive_border_color #49454e
url_color             #d0bcff

active_tab_foreground   #391e72
active_tab_background   #d0bcff
inactive_tab_foreground #cac4cf
inactive_tab_background #49454e
cursor_trail_color      #cac4cf
