################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,2880x1920@60,auto,1.5

# -- DO NOT MANUALLY ALTER BELOW THIS POINT; IT COULD BREAK YOUR MONITOR CONFIGURATION --

# Execute a script to assign 3 permanent workspaces per monitor
exec-once=~/.config/hypr/conf.d/scripts/create_workspaces.sh 
workspace=1, monitor:eDP-1
workspace=2, monitor:eDP-1
workspace=3, monitor:eDP-1
workspace=1, monitor:eDP-1
workspace=2, monitor:eDP-1
workspace=3, monitor:eDP-1
