################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,2880x1920@60,auto,1.5

exec-once=~/.config/hypr/conf.d/scripts/create_workspaces.sh 
workspace=1, monitor:eDP-1
workspace=2, monitor:eDP-1
workspace=3, monitor:eDP-1
