# custom file template i made for snappy

[theme]
background = #121316
card_bg = #1e1f23
card_selected = #283141
border_color = #aac7ff
text_color = #e3e2e6
badge_bg = #00458d
badge_text_color = #e3e2e6
bundle_bg = #00458d
border_width = 2
corner_radius = 20
