hl.on("hyprland.start", function () 
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("easyeffects --gapplication-service")
	hl.exec_cmd("qs -c noctalia-shell")
	hl.exec_cmd("hyprpm reload -n")
	hl.exec_cmd("hyprctl setcursor DOT-dark 24")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
end)
