hl.on("hyprland.start", function () 
	hl.exec_cmd("easyeffects --gapplication-service")
	hl.exec_cmd("qs -c noctalia-shell")
	hl.exec_cmd("hyprpm reload -n")
	hl.exec_cmd("hyprctl setcursor Remus-Black 32")
	hl.exec_cmd("wl-clip-persist --clipboard regular")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme 'Remus-Black'")
	hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-size 32")
end)
