hl.env("XCURSOR_SIZE", "32")
hl.env("HYPRCURSOR_SIZE", "32")
hl.env("XCURSOR_THEME", "Remus-Black")
hl.env("HYPRCURSOR_THEME", "Remus-Black")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
