# custom file template i made for snappy

[theme]
background = {{colors.background.default.hex}}
card_bg = {{colors.surface_container.default.hex}}
card_selected = {{colors.on_secondary.default.hex}}
border_color = {{colors.primary.default.hex}}
text_color = {{colors.on_surface.default.hex}}
badge_bg = {{colors.primary_container.default.hex}}
badge_text_color = {{colors.on_surface.default.hex}}
bundle_bg = {{colors.primary_container.default.hex}}
border_width = 2
corner_radius = 0
