hl.on("hyprland.start", function () 
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("easyeffects")
	hl.exec_cmd("qs -c noctalia-shell")
	hl.exec_cmd("hyprpm reload -n")
	hl.exec_cmd("hyptctl setcursor DOT-dark 24")
end)
