#################
### AUTOSTART ###
#################

# Daemons
exec-once = systemctl --user start hyprpolkitagent
exec-once = awww-daemon
exec-once = snappy-switcher --daemon

# Background Apps
exec-once = easyeffects --gapplication-service
exec-once = qs -c noctalia-shell

# Preliminary Scripts
exec-once = sh ~/.config/hypr/conf.d/scripts/create_workspaces.sh

# Packages and Styling
exec-once = hyprpm reload -n
exec-once = hyprctl setcursor DOT-dark 24

# Startup Applications
