################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
exec-once=~/.config/hypr/conf.d/scripts/create_workspaces.sh 
workspace=2, monitor:eDP-1, persistent:true
workspace=3, monitor:eDP-1, persistent:true
workspace=1, monitor:eDP-1, persistent:true
workspace=2, monitor:eDP-1, persistent:true
workspace=3, monitor:eDP-1, persistent:true
